apiVersion: v1  
kind: Service                           
metadata:
  name: deallapp-mysql             
  labels:                              
    app: deallapp-mysql
spec:
  type: NodePort                       
  selector:
    app: deallapp-mysql            
  ports: 
  - name: http
    port: 8080
    targetPort: 8080