version: '3'
services:
  app:
    container_name: app_go
    build: .
    ports: 
      - 8080:8080 
    restart: on-failure
    volumes:
      - api:/usr/src/app/
    depends_on:
      - db-mysql
    networks:
      - deallnet


  db-mysql:
    image: mysql:5.7
    container_name: db_mysql
    ports: 
      - 3306:3306
    environment: 
      - MYSQL_ROOT_HOST=${DB_HOST} 
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    volumes:
      - store_mysql:/var/lib/mysql
    networks:
      - deallnet
  
  pma:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    depends_on:
      - db-mysql
    environment:
      - PMA_HOST=db-mysql
      - PMA_USER=${DB_USER}
      - PMA_PORT=${DB_PORT}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - 9090:80
    restart: always
    networks:
      - deallnet

volumes:
  api:
  store_mysql:                  

networks:
  deallnet:
    driver: bridge