apiVersion: v1                           
kind: Service                            
metadata:
  name: db-mysql                 
  labels:                                
    app: db-mysql
spec:
  type: NodePort
  ports:
    - port: 3306
  selector:                              
    app: db-mysql
    tier: mysql 