apiVersion: v1
kind: PersistentVolume                      
metadata:
  name: mysql-db-pv
  labels:
    type: local
    app: db-mysql
spec:
  storageClassName: manual                 
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:                                 
    path: "/mnt/data"
  persistentVolumeReclaimPolicy: Retain     