apiVersion: v1
kind: PersistentVolumeClaim             
metadata:                              
  name: mysql-db-pvc
  labels:
    app: db-mysql
spec:                                   
  storageClassName: manual              
  accessModes:
    - ReadWriteMany                    
  resources:
    requests:
      storage: 5Gi